### ISSUE TITLE
Nokogiri not working straight out of the box (module not found)

### ISSUE THREAD

**Issue by Faelwen** [ActiveState/activeruby#3]
### My setup:
- Windows 10 x64
- Fresh install of ActiveRuby-2.3.4.0-beta-win64 (complete install)

### Description of the issue
If I try to launch the following code:
```
require 'nokogiri'
xml_doc  = Nokogiri::XML("<root><aliens><alien><name>Alf</name></alien></aliens></root>")
puts "Parsing complete"
```
I get the following error:

```
C:/ActiveRuby/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': 126: Le module spÚcifiÚ est introuvable.   - C:/ActiveRuby/lib/ruby/gems/2.3.0/gems/nokogiri-1.8.0/lib/nokogiri/nokogiri.so (LoadError)
        from C:/ActiveRuby/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/ActiveRuby/lib/ruby/gems/2.3.0/gems/nokogiri-1.8.0/lib/nokogiri.rb:32:in `rescue in <top (required)>'
        from C:/ActiveRuby/lib/ruby/gems/2.3.0/gems/nokogiri-1.8.0/lib/nokogiri.rb:28:in `<top (required)>'
        from C:/ActiveRuby/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
        from C:/ActiveRuby/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
        from C:/ActiveRuby/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from test_nokogiri.rb:1:in `<main>'
```
Which basically means that ruby cannot find the nokogiri module.

However, if I check with "gem list", nokogiri does appear to be installed:
```
*** LOCAL GEMS ***

actioncable (5.1.2)
actionmailer (5.1.2)
actionpack (5.1.2)
actionview (5.1.2)
activejob (5.1.2)
activemodel (5.1.2)
activerecord (5.1.2)
activesupport (5.1.2)
addressable (2.5.1)
arel (8.0.0)
aws-sdk (2.10.10)
aws-sdk-core (2.10.10)
aws-sdk-resources (2.10.10)
aws-sigv4 (1.0.1)
backports (3.8.0)
bigdecimal (1.2.8)
bindex (0.5.0)
bson (4.2.2)
builder (3.2.3)
bundler (1.15.1)
byebug (9.0.6)
cassandra-driver (3.2.0)
childprocess (0.7.1)
concurrent-ruby (1.0.5)
cucumber (2.4.0)
cucumber-core (2.0.0, 1.5.0)
cucumber-wire (0.0.1)
dalli (2.7.6)
did_you_mean (1.0.0)
diff-lcs (1.3)
docile (1.1.5)
erubi (1.6.1)
erubis (2.7.0)
excon (0.57.1)
ffi (1.9.18)
gherkin (4.1.3)
globalid (0.4.0)
heroku-api (0.4.2)
hoe (3.16.0)
i18n (0.8.6)
ice_nine (0.11.2)
io-console (0.4.5)
ione (1.2.4)
jmespath (1.3.1)
json (2.1.0, 1.8.3)
little-plugger (1.1.4)
log4r (1.1.10)
logging (2.2.2)
loofah (2.0.3)
mail (2.6.6)
method_source (0.8.2)
mime-types (3.1)
mime-types-data (3.2016.0521)
mini_portile2 (2.2.0)
minitest (5.10.2, 5.8.5)
money (6.9.0)
mongo (2.4.2)
multi_json (1.12.1)
multi_test (0.1.2)
mustermann (1.0.0)
mysql2 (0.4.8)
net-telnet (0.1.1)
nio4r (2.1.0)
nokogiri (1.8.0)
path_expander (1.0.2)
pg (0.21.0)
pkg-config (1.1.9)
power_assert (0.2.6)
psych (2.1.0)
public_suffix (2.0.5)
puma (3.9.1)
rack (2.0.3)
rack-protection (2.0.0)
rack-test (0.7.0, 0.6.3)
rails (5.1.2)
rails-dom-testing (2.0.3)
rails-html-sanitizer (1.0.3)
railties (5.1.2)
rake (12.0.0, 10.4.2)
rake-compiler (1.0.4)
rb-readline (0.5.4)
rdoc (5.1.0, 4.2.1)
redis (3.3.3)
rubyzip (1.2.1)
selenium-webdriver (3.4.4)
sexp_processor (4.9.0)
simplecov (0.14.1)
simplecov-html (0.10.1)
sinatra (2.0.0)
sixarm_ruby_unaccent (1.1.2)
sprockets (3.7.1)
sprockets-rails (3.2.0)
sqlite3 (1.3.13)
test-unit (3.1.5)
thor (0.19.4)
thread_safe (0.3.6)
tilt (2.0.7)
tzinfo (1.2.3)
tzinfo-data (1.2017.2)
websocket-driver (0.6.5)
websocket-extensions (0.1.2)
xmlrpc (0.3.0)
```

### Solving the issue
Reinstalling nokogiri with "gem install nokogiri" will solve the issue and relaunching my script will give the expected output:
`Parsing complete`

I notice the nokogiri gem will have a slightly different name in "gem list":
`nokogiri (1.8.0 ruby x64-mingw32)`

Perhaps the x64 version of the module is missing in the win64 build of ActiveRuby, causing the problem in my particular case?

### Repeatability
- Once nokogiri has been mannualy reinstalled,  deinstalling and reinstalling ActiveRuby wil not reproduce the issue.
- However, if the C:\ActiveRuby folder is deleted after deinstalling, the issue will reproduce when ActiveRuby is reinstalled.

**Comment by rawktron** [comment]
Thanks for the super detailed feedback - this is really helpful - will pass along to devs and will get this looked at!
